language: python
env:
  #- USE_CLIENT_SECRET=True
  - USE_CLIENT_SECRET=False
python:
  - "2.7"
  - "3.6"

before_install:
    - python -m pip install --upgrade setuptools pip virtualenv

# command to install dependencies
install:
  - python -m pip install -r requirements_test.txt --upgrade
  - python -m pip install -e .

# command to run tests
script:
    - python -m unittest warrant.tests.tests
    - python setup.py bdist_wheel --universal
